FROM ubuntu:14.04
MAINTAINER Norio Nomura <norio.nomura@gmail.com>

# Install Dependencies

RUN apt-get update && \
    apt-get install -y \
      clang-3.5 \
      git \
      libblocksruntime0 \
      libedit2 \
      libicu52 \
      libkqueue0 \
      libpython2.7-dev \
      libxml2 \
      python2.7 \
      && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 100 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
