FROM ubuntu:15.10
MAINTAINER Norio Nomura <norio.nomura@gmail.com>

# Install Dependencies

RUN apt-get update && \
    apt-get install -y \
      clang \
      git \
      libblocksruntime0 \
      libedit2 \
      libkqueue0 \
      libxml2 \
      python2.7 \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
